AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env: 
    Type: String
    Default: stg
  	
Resources:
  ELBLB2630I:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
      Properties:
        Subnets:
          - "subnet-82f545f9"
        Scheme: "internal
        Listeners:
          InstancePort: 80
          LoadBalancerPort: 80
          Potocol: HTTP
        SecurityGroups:
          - "launch-wizard-4"
        Tags:
        - Key: "Env"
        Value: !Ref Env
	

